In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("/content/train.csv")

In [4]:
df.head()

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0

In [6]:
df.shape

(404290, 6)

In [4]:
df.dropna(inplace=True)

In [5]:
df = df.sample(40000)

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [8]:
ques_df = df[['question1','question2']]
ques_df.head()

,question1,question2
207986,If the universe is flat how could you see star...,How do you describe the look-and-feel stylings...
318614,How does Ed Sheeran strum Kiss Me?,Was Ed Sheeran a good student in school?
394692,How do I correct the information entered in a ...,In a world where we are overloaded by informat...
112911,What will happen when two black holes come tog...,What will happen when two black holes come tog...
299490,Are there stories of gold-diggers who married ...,Do most ivy league or ivy league-caliber alumn...

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

questions = list(ques_df['question1']) + list(ques_df['question2'])

cv = CountVectorizer(max_features=3000)
q1_arr, q2_arr = np.vsplit(cv.fit_transform(questions).toarray(),2)

In [10]:
temp_df1 = pd.DataFrame(q1_arr, index= ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index= ques_df.index)
temp_df = pd.concat([temp_df1, temp_df2], axis=1)
temp_df.shape

(40000, 6000)

In [11]:
temp_df['is_duplicate'] = df['is_duplicate']

In [12]:
temp_df.head()

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
207986,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
318614,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
394692,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
112911,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
299490,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
X = temp_df.drop(columns= ['is_duplicate'])
y = temp_df["is_duplicate"]

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.2)

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7497

In [16]:
from sklearn.metrics import accuracy_score

In [17]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train.values,y_train.values)
y_pred = xgb.predict(X_test.values)
accuracy_score(y_test,y_pred)

0.73275